[tool.poetry]
name = "mqsrv"
version = "0.1.0"
description = ""
authors = ["daleydeng <daleydeng@qingtong123.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
